### ISSUE TITLE
Did spotify change something? This tool cannot download music anymore, and it reports 403 error.

### ISSUE THREAD

**Issue by xyb921866260** [DevLARLEY/spotify-oggmp4-dl#2]

**Comment by DevLARLEY** [comment]
Spotify is just upgrading their security. 
+ If you're getting a 403 on widevine, use a different WVD.
+ If you're getting a 403 on playplay, recompile the linked code (I changed the link at some point, as the older decryptor does not work anymore)

**Comment by xyb921866260** [comment]
The request result is 403 at this step:
` playplay_request = requests.post(
                url=f"https://gew4-spclient.spotify.com/playplay/v1/key/{file_id}",
                headers={
                    "Authorization": f"Bearer {self.token_manager.get_access_token()}",
                },
                data=playplay_license_request.SerializeToString(),
                verify=False
            )`

**Comment by xyb921866260** [comment]
> Spotify is just upgrading their security.
> 
> * If you're getting a 403 on widevine, use a different WVD.
> * If you're getting a 403 on playplay, recompile the linked code (I changed the link at some point, as the older decryptor does not work anymore)

The request result is 403 at this step:
`            playplay_request = requests.post(
                url=f"https://gew4-spclient.spotify.com/playplay/v1/key/{file_id}",
                headers={
                    "Authorization": f"Bearer {self.token_manager.get_access_token()}",
                },
                data=playplay_license_request.SerializeToString(),
                verify=False
            )`

**Comment by DevLARLEY** [comment]
As I said, you need to recompile [this](https://git.gay/uhwot/unplayplay)

**Comment by xyb921866260** [comment]
> As I said, you need to recompile [this](https://git.gay/uhwot/unplayplay)

403 again
